version: '3.8'

services:

  rest-app:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/app/
    ports:
      - "8000:8000"
    command: uvicorn app.rest.run:app --reload --host 0.0.0.0
